spring:
  application:
    name: study8-gateway
  cloud:
    gateway:
      routes:
        - id: study8-sys-auth
          uri: lb://study8-sys
          predicates:
            - Path=/sys/api/v1/auth/**
server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
