spring:
  application:
    name: study8-gateway
  cloud:
    gateway:
      routes:
        - id: study8-sys-auth
          uri: ${EUREKA_ROUTES_URI:lb://study8-sys}
          predicates:
            - Path=/sys/api/v1/auth/**
server:
  port: 8300
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:https://study8:2024study8@study8.onrender.com/eureka/}
  instance:
    hostname: localhost
    prefer-ip-address: true