spring:
  application:
    name: study8-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: localhost
    prefer-ip-address: true
jwt:
  secret: ${JWT_SECRET}
study8:
  sys:
    uri: ${STUDY8_SYS_URI}
server:
  port: 8300