spring:
  application:
    name: study8-gateway
  cloud:
    gateway:
      routes:
        - id: study8-sys-auth
          uri: ${EUREKA_ROUTES_URI:lb://study8-sys}
          predicates:
            - Path=/sys/api/v1/auth/**
        - id: study8-sys-system
          uri: ${EUREKA_ROUTES_URI:lb://study8-sys}
          predicates:
            - Path=/sys/api/v1/system/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://study8:study82024@localhost:8761/eureka/}
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8300