spring:
  application:
    name: study8-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8300