spring:
  application:
    name: study8-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://study8:study82024@localhost:8761/eureka/}
  instance:
    hostname: localhost
    prefer-ip-address: true
jwt:
  secret: ${JWT_SECRET}
study8:
  sys:
    uri: ${STUDY8_SYS_URI:lb://study8-sys}
server:
  port: 8300