spring:
  application:
    name: study8-gateway
  cloud:
    gateway:
      routes:
        - id: study8-sys-auth
          uri: ${EUREKA_ROUTES_URI}
          predicates:
            - Path=/sys/api/v1/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8300