eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://study8:study82024@localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    prefer-ip-address: true
spring:
  application:
    name: study8-sys
  devtools:
    livereload:
      enabled: false
  cache:
    type: caffeine
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 8200
encryption:
  algorithm: ${ENCRYPTION_ALGORITHM:AES/CBC/PKCS5Padding}
  key: ${ENCRYPTION_KEY:aesEncryptionKey}
  iv: ${ENCRYPTION_IV:encryptionIntVec}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE