eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
    prefer-ip-address: true
spring:
  application:
    name: study8-sys
  devtools:
    livereload:
      enabled: false
  cache:
    type: caffeine
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      leakDetectionThreshold: 2000
      data-source-properties:
        cachePrepStmts: false
        prepStmtCacheSize: 0
        useServerPrepStmts: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
    hibernate:
      ddl-auto: none
    open-in-view: false
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    port: 25
server:
  port: 8200
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE