eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: study8-api
  security:
    user:
      password: ${SECURITY_PASSWORD:study82024}
      name: ${SECURITY_USERNAME:study8}
logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: 8761