eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
spring:
  application:
    name: study8-api
  security:
    user:
      password: ${SECURITY_PASSWORD}
      name: ${SECURITY_USERNAME}
logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: 8761