eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:study8.onrender.com}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:https://study8.onrender.com/eureka/}
spring:
  application:
    name: study8-api
  security:
    user:
      password: 2024study8
      name: study8
logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: 8761